Added binary marshal serialization protocol
mapsme/Alohalytics pull request #52
Opened 2020-09-18 15:09 UTC by burivuh

add marshal binary serialisation between worker and aggregator
protocol refactoring

2020-09-18 16:48 UTC, jbenua requested changes
не поняла только, зачем тут файл `snippets/pyaloha/protocol/python.py`

2020-09-18 16:48 UTC, jbenua commented on snippets/pyaloha/base.py
>  to optional access of the same routine of instantiating same data properties.
а чо с форматированием докстрингов?

2020-09-18 16:48 UTC, jbenua commented on snippets/pyaloha/protocol/basic_json.py
> +            logger.error('Corrupted json:\n%s' % data)
format? не настаиваю
но если процентик, то через зпт

2020-09-18 16:48 UTC, jbenua commented on snippets/pyaloha/protocol/basic_marshal.py
> +
\+ строка

2020-09-21 13:28 UTC, burivuh commented on snippets/pyaloha/base.py
>  to optional access of the same routine of instantiating same data properties.
done

2020-09-21 13:28 UTC, burivuh commented on snippets/pyaloha/protocol/basic_json.py
> +            logger.error('Corrupted json:\n%s' % data)
done

2020-09-21 13:28 UTC, burivuh commented on snippets/pyaloha/protocol/basic_marshal.py
> +
done

2020-09-21 17:38 UTC, jbenua requested changes

2020-09-21 17:38 UTC, jbenua commented on snippets/pyaloha/protocol/basic_marshal.py
> +
really?:)

2020-09-21 17:38 UTC, jbenua commented on snippets/pyaloha/protocol/basic_json.py
> +            logger.error('Corrupted json:\n%s' % data)
где?:)

2020-09-21 17:38 UTC, jbenua commented on snippets/pyaloha/ccode.py
\+ строка

2020-09-22 07:58 UTC, burivuh commented on snippets/pyaloha/protocol/basic_marshal.py
> +
yeah?

2020-09-22 08:41 UTC, jbenua requested changes

2020-09-22 08:41 UTC, jbenua commented on snippets/pyaloha/protocol/basic_marshal.py
> +
![image](https://user-images.githubusercontent.com/3294891/93860953-7a13d400-fcc8-11ea-9bf9-b35edd7095da.png)

2020-09-22 08:41 UTC, jbenua commented on snippets/pyaloha/protocol/basic_json.py
> +
\- строка

2020-09-30 10:41 UTC, jbenua approved these changes

2020-09-30 10:41 UTC, merged